.unit_tests:
  image: registry.tooling.prd.eu.olx.org/library/python:3.11-alpine
  before_script:
    - pip install pipenv
    - apk add --no-cache gcc python3-dev musl-dev linux-headers
    - pip install psutil
    - pipenv install --dev
    - export PYTHONPATH=$(which python):$PYTHONPATH
  script:
    - pipenv run pytest tests/* --cov=src/ --cov-report=term --cov-report=html --cov-report=xml --cov-fail-under=80 -vvv
  artifacts:
    paths:
      - coverage.xml
      - htmlcov/
    expire_in: 1 week

unit_tests:
  stage: test
  extends:
    - .unit_tests

